### Criar um Novo Aluno
POST http://localhost:5000/students
Content-Type: application/json

{
  "name": "Arthur Feu",
  "email": "arthurfeufeu@gmail.com",
  "ra": "67890123",
  "cpf": "123.456.789-10"
}

### Listar Todos os Alunos
GET http://localhost:5000/students
